In [127]:
import numpy as np
from numpy.linalg import inv

In [122]:
def Euler(x0,T,dx):
    x1 = x0 + f(x0,T,dx)
    x2 = x1 + f(x1,T,dx)
    return x2

# Runge-Kutta

In [112]:
def f(x0,T,dx):
    #print (x0,"T",T)
    x1 = T*np.dot(dx,x0) # + x0
    return x1

In [124]:
def RungeKutta(x0,dx,T,te,t0=0):
    xk=x0
    tk=0
    if te==T:
        te=te+0.1
    for t in np.arange(t0, te, T):
        if t == t0:
            continue
        m1 = f(xk,tk,dx)
        m2 = f(xk+T/2*m1,tk+T/2,dx)
        m3 = f(xk+T/2*m2,tk+T/2,dx)
        m4 = f(xk+T*m3,tk+T,dx)
        x = xk + T/6*(m1+2*m2+2*m3+m4)
        xk = x
    return xk

In [125]:
x0 = np.array([[1],[0]])
dx = np.array([[0,1],[-10,-5]])
te = 0.4
T = 0.4

In [126]:
print (RungeKutta(x0,dx,T,te))

[[ 0.97226667]
 [-0.6528    ]]


# Trapezni postupak

In [128]:
def trapese(A,B,x0,T,te,t0=0):
    U = np.ones(x0.shape)
    assert(A.shape==U.shape)
    assert(A.shape==B.shape)
    R = np.dot(inv(U-A*T/2),U+A*T/2)#((U-A*T/2)^-1)(U+A*T/2)
    S = np.dot(inv(U-A*T/2),B*T/2) #((U-A*T/2)^-1)*T/2*B
    x = R*xk + S*(r(tk)+r(tk1))


In [28]:
dx = np.array([[0,1],[-10,-5]])

In [5]:
dx

array([[ 0,  1],
       [-1,  0]])

In [11]:
x0 = np.array([[1],[0]])
print (x0)
T = 0.4

[[1]
 [0]]


In [15]:
x1 = x0 + dx*T

In [16]:
print (xk)

[[ 1.   1.4]
 [-0.4  0. ]]


In [17]:
dx*T

array([[ 0. ,  0.4],
       [-0.4,  0. ]])

In [19]:
np.dot(dx,T)

array([[ 0. ,  0.4],
       [-0.4,  0. ]])

In [24]:
np.ones(x0.shape)*T

array([[ 0.4,  0.4]])

In [26]:
np.dot(dx,np.ones(x0.shape)*T)

array([[ 0.4],
       [-0.4]])

In [32]:
x1 = x0 + T*np.dot(dx,x0)
print(x1)

[[ 1.]
 [-4.]]


In [35]:
x2 = x1 + T*np.dot(dx,x1)
print(x2)

[[-0.6]
 [ 0. ]]


In [38]:
def f(x0,T):
    x1 = x0 + T*np.dot(dx,x0)
    return x1 

In [39]:
print(f(x0,T))

[[ 1.]
 [-4.]]


In [40]:
print(f(x1,T))

[[-0.6]
 [ 0. ]]


In [48]:
np.arange(0.0, 1.0, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [110]:
x0 = np.array([[1],[0]])
dx = np.array([[0,1],[-10,-5]])
te = 0.4
T = 0.4

In [123]:
print(Euler(x0,T,dx))

[[-0.6]
 [ 0. ]]


In [62]:
print (RungeKutta(x0,dx,T,te))

[[ 1.44992   ]
 [-0.97322667]]


In [76]:
np.arange(0, 0.4, 0.4)

array([ 0.])

In [77]:
np.arange(0, 0.5, 0.4)

array([ 0. ,  0.4])